// Generated by tools/genfont.c -- do not edit by hand.
//
// The glyph data this indexes is rasterized from JetBrains Mono:
//   Copyright 2020 The JetBrains Mono Project Authors
//   https://github.com/JetBrains/JetBrainsMono
// It is a Modified Version of that Font Software and is licensed under
// the SIL Open Font License 1.1 -- see NOTICE and licenses/ -- not under
// ztabb's MIT licence.
// Glyph coverage lives in font.dat: 1067 glyphs per section,
// one byte per pixel, sections listed below.
// Baked from JetBrains Mono.

pub const glyph_count: usize = 1067;

/// 0 = regular, 1 = bold, 2 = medium.
pub const Section = struct {
    w: u32,
    h: u32,
    weight: u8,
    /// Point size this section was rasterized for, at 1x.
    points: u32,
    density: u32,
    offset: usize,
};

pub const sections = [_]Section{
    .{ .w = 6, .h = 13, .weight = 2, .points = 10, .density = 1, .offset = 0 },
    .{ .w = 7, .h = 15, .weight = 2, .points = 11, .density = 1, .offset = 83226 },
    .{ .w = 8, .h = 17, .weight = 2, .points = 13, .density = 1, .offset = 195261 },
    .{ .w = 7, .h = 15, .weight = 0, .points = 11, .density = 1, .offset = 340373 },
    .{ .w = 7, .h = 15, .weight = 1, .points = 11, .density = 1, .offset = 452408 },
    .{ .w = 8, .h = 17, .weight = 0, .points = 13, .density = 1, .offset = 564443 },
    .{ .w = 8, .h = 17, .weight = 1, .points = 13, .density = 1, .offset = 709555 },
    .{ .w = 10, .h = 21, .weight = 0, .points = 16, .density = 1, .offset = 854667 },
    .{ .w = 10, .h = 21, .weight = 1, .points = 16, .density = 1, .offset = 1078737 },
    .{ .w = 12, .h = 26, .weight = 2, .points = 10, .density = 2, .offset = 1302807 },
    .{ .w = 14, .h = 30, .weight = 2, .points = 11, .density = 2, .offset = 1635711 },
    .{ .w = 16, .h = 34, .weight = 2, .points = 13, .density = 2, .offset = 2083851 },
    .{ .w = 14, .h = 30, .weight = 0, .points = 11, .density = 2, .offset = 2664299 },
    .{ .w = 14, .h = 30, .weight = 1, .points = 11, .density = 2, .offset = 3112439 },
    .{ .w = 16, .h = 34, .weight = 0, .points = 13, .density = 2, .offset = 3560579 },
    .{ .w = 16, .h = 34, .weight = 1, .points = 13, .density = 2, .offset = 4141027 },
    .{ .w = 20, .h = 42, .weight = 0, .points = 16, .density = 2, .offset = 4721475 },
    .{ .w = 20, .h = 42, .weight = 1, .points = 16, .density = 2, .offset = 5617755 },
};

/// Terminal point sizes, smallest first; the middle one is the default.
pub const term_points = [_]u32{
    11,
    13,
    16,
};
/// The interface size that goes with each terminal size.
pub const ui_points = [_]u32{
    10,
    11,
    13,
};

pub const Range = struct { lo: u21, hi: u21, base: u16 };

pub const ranges = [_]Range{
    .{ .lo = 0x0020, .hi = 0x007E, .base = 0 },
    .{ .lo = 0x00A0, .hi = 0x00FF, .base = 95 },
    .{ .lo = 0x0400, .hi = 0x045F, .base = 191 },
    .{ .lo = 0x2010, .hi = 0x2027, .base = 287 },
    .{ .lo = 0x2190, .hi = 0x21AF, .base = 311 },
    .{ .lo = 0x2500, .hi = 0x257F, .base = 343 },
    .{ .lo = 0x2580, .hi = 0x259F, .base = 471 },
    .{ .lo = 0x25A0, .hi = 0x25FF, .base = 503 },
    .{ .lo = 0x2600, .hi = 0x27BF, .base = 599 },
    .{ .lo = 0xE0A0, .hi = 0xE0B3, .base = 1047 },
};
