// Generated by tools/genfont.c -- do not edit by hand.
// Glyph coverage lives in font.dat: 1067 glyphs per weight,
// two weights per size, one byte per pixel.

pub const glyph_count: usize = 1067;

pub const Size = struct {
    w: u32,
    h: u32,
    /// Byte offset of the regular weight within font.dat.
    offset: usize,
};

pub const sizes = [_]Size{
    .{ .w = 8, .h = 16, .offset = 0 },
    .{ .w = 16, .h = 32, .offset = 273152 },
};

pub const Range = struct { lo: u21, hi: u21, base: u16 };

pub const ranges = [_]Range{
    .{ .lo = 0x0020, .hi = 0x007E, .base = 0 },
    .{ .lo = 0x00A0, .hi = 0x00FF, .base = 95 },
    .{ .lo = 0x0400, .hi = 0x045F, .base = 191 },
    .{ .lo = 0x2010, .hi = 0x2027, .base = 287 },
    .{ .lo = 0x2190, .hi = 0x21AF, .base = 311 },
    .{ .lo = 0x2500, .hi = 0x257F, .base = 343 },
    .{ .lo = 0x2580, .hi = 0x259F, .base = 471 },
    .{ .lo = 0x25A0, .hi = 0x25FF, .base = 503 },
    .{ .lo = 0x2600, .hi = 0x27BF, .base = 599 },
    .{ .lo = 0xE0A0, .hi = 0xE0B3, .base = 1047 },
};
