// Generated by tools/genfont.c -- do not edit by hand.
// Glyph coverage lives in font.dat: 1067 glyphs per section,
// one byte per pixel, sections listed below.

pub const glyph_count: usize = 1067;

/// 0 = regular, 1 = bold, 2 = medium.
pub const Section = struct {
    w: u32,
    h: u32,
    weight: u8,
    offset: usize,
};

pub const sections = [_]Section{
    .{ .w = 7, .h = 14, .weight = 2, .offset = 0 },
    .{ .w = 8, .h = 16, .weight = 0, .offset = 104566 },
    .{ .w = 8, .h = 16, .weight = 1, .offset = 241142 },
    .{ .w = 14, .h = 28, .weight = 2, .offset = 377718 },
    .{ .w = 16, .h = 32, .weight = 0, .offset = 795982 },
    .{ .w = 16, .h = 32, .weight = 1, .offset = 1342286 },
};

pub const Range = struct { lo: u21, hi: u21, base: u16 };

pub const ranges = [_]Range{
    .{ .lo = 0x0020, .hi = 0x007E, .base = 0 },
    .{ .lo = 0x00A0, .hi = 0x00FF, .base = 95 },
    .{ .lo = 0x0400, .hi = 0x045F, .base = 191 },
    .{ .lo = 0x2010, .hi = 0x2027, .base = 287 },
    .{ .lo = 0x2190, .hi = 0x21AF, .base = 311 },
    .{ .lo = 0x2500, .hi = 0x257F, .base = 343 },
    .{ .lo = 0x2580, .hi = 0x259F, .base = 471 },
    .{ .lo = 0x25A0, .hi = 0x25FF, .base = 503 },
    .{ .lo = 0x2600, .hi = 0x27BF, .base = 599 },
    .{ .lo = 0xE0A0, .hi = 0xE0B3, .base = 1047 },
};
